/**
 * Canvas synthesis for LightPic — Template 1: "Sunny Outdoor"
 *
 * Inputs: a base image (lifestyle-scene generated by Replicate, no text)
 *         + structured copy (titles, bullets, badges) generated by Claude.
 *
 * Output: a 750×750 PNG dataURL ready for Pinduoduo upload.
 *
 * Layout (matches the user's reference image #4):
 *
 *   ┌──────────────────────────────────────┐ 750×750
 *   │  ✦ MAIN TITLE (8-14 char)            │
 *   │    SUB TITLE                         │
 *   │    ✓ bullet  ✓ bullet  ✓ bullet      │
 *   │                                      │
 *   │  ┌──────┐               麦穗 badge   │
 *   │  │ NEW  │              ─────────     │
 *   │  └──────┘               麦穗 badge   │
 *   │                                      │
 *   │            (product hero)            │
 *   │                                      │
 *   │  brand                               │
 *   └──────────────────────────────────────┘
 *
 * Fonts: loaded via Google Fonts <link> in layout.tsx — we wait for
 * document.fonts.ready before drawing. System fallback handles SSR.
 */

export type CopyData = {
  main_title: string;
  sub_title: string;
  bullets: string[];
  side_badges: string[];
  new_badge: string;
  brand: string;
};

const CANVAS_SIZE = 750;

/**
 * Resolve the Noto Sans SC family that next/font registered (it gets a
 * hashed family name like "__Noto_Sans_SC_xxx"). We read the CSS
 * variable from <html>; if anything fails, fall back to system fonts.
 */
function getFontFamily(): string {
  if (typeof document === "undefined") {
    return '"PingFang SC", "Heiti SC", "Microsoft YaHei", sans-serif';
  }
  const cssVar = getComputedStyle(document.documentElement)
    .getPropertyValue("--font-noto-sans-sc")
    .trim();
  if (cssVar) {
    return `${cssVar}, "PingFang SC", "Heiti SC", "Microsoft YaHei", sans-serif`;
  }
  return '"Noto Sans SC", "PingFang SC", "Heiti SC", "Microsoft YaHei", sans-serif';
}

/** Load an HTMLImageElement from a URL (handles CORS for cross-origin Replicate URLs). */
function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Failed to load image: ${url}`));
    img.src = url;
  });
}

/** Draw a cover-fit image (like CSS background-size: cover) into a square. */
function drawCover(
  ctx: CanvasRenderingContext2D,
  img: HTMLImageElement,
  size: number,
) {
  const ratio = Math.max(size / img.width, size / img.height);
  const w = img.width * ratio;
  const h = img.height * ratio;
  const x = (size - w) / 2;
  const y = (size - h) / 2;
  ctx.drawImage(img, x, y, w, h);
}

/** Draw a soft semi-transparent gradient at the top to make text readable. */
function drawTopScrim(ctx: CanvasRenderingContext2D, size: number) {
  const grad = ctx.createLinearGradient(0, 0, 0, size * 0.45);
  grad.addColorStop(0, "rgba(255,255,255,0.55)");
  grad.addColorStop(1, "rgba(255,255,255,0)");
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, size, size * 0.45);
}

/** Draw the main title at top, with auto line-break if too long. */
function drawMainTitle(
  ctx: CanvasRenderingContext2D,
  text: string,
  size: number,
  fontFamily: string,
) {
  ctx.fillStyle = "#1A1A1A";
  ctx.textBaseline = "top";
  ctx.textAlign = "left";
  // Big, heavy title — Pinduoduo style
  ctx.font = `900 56px ${fontFamily}`;
  ctx.shadowColor = "rgba(255,255,255,0.6)";
  ctx.shadowBlur = 4;
  // Break to two lines if longer than ~9 chars (Chinese)
  const padding = 36;
  const maxChars = 9;
  let line1 = text;
  let line2 = "";
  if (text.length > maxChars) {
    // try to split at a sensible breakpoint (space first, else mid)
    const spaceIdx = text.indexOf(" ", Math.floor(text.length / 2) - 2);
    const splitAt = spaceIdx > 0 ? spaceIdx : Math.ceil(text.length / 2);
    line1 = text.slice(0, splitAt).trim();
    line2 = text.slice(splitAt).trim();
  }
  ctx.fillText(line1, padding, 32);
  if (line2) ctx.fillText(line2, padding, 32 + 64);
  ctx.shadowBlur = 0;
}

/** Draw subtitle (smaller, e.g. "SPF50+ PA++++") below main title. */
function drawSubTitle(
  ctx: CanvasRenderingContext2D,
  text: string,
  hasTwoLineMain: boolean,
  fontFamily: string,
) {
  if (!text) return;
  ctx.fillStyle = "#1A1A1A";
  ctx.textBaseline = "top";
  ctx.textAlign = "left";
  ctx.font = `700 32px ${fontFamily}`;
  const y = hasTwoLineMain ? 32 + 64 + 70 : 32 + 70;
  ctx.fillText(text, 36, y);
}

/** Draw the 3-bullet checkmark row below the subtitle. */
function drawBullets(
  ctx: CanvasRenderingContext2D,
  bullets: string[],
  hasTwoLineMain: boolean,
  hasSubTitle: boolean,
  fontFamily: string,
) {
  if (!bullets?.length) return;
  ctx.textBaseline = "middle";
  ctx.textAlign = "left";
  ctx.font = `500 20px ${fontFamily}`;
  ctx.fillStyle = "#1A1A1A";
  let y = 32;
  if (hasTwoLineMain) y += 64;
  y += 70;
  if (hasSubTitle) y += 50;
  let x = 36;
  for (const b of bullets.slice(0, 3)) {
    // checkmark
    ctx.strokeStyle = "#1A1A1A";
    ctx.lineWidth = 2.5;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(x + 6, y + 6);
    ctx.lineTo(x + 16, y - 6);
    ctx.stroke();
    // text
    const textX = x + 24;
    ctx.fillText(b, textX, y);
    const w = ctx.measureText(b).width;
    x = textX + w + 28;
  }
}

/** Draw a circular NEW-style badge in the upper-left area. */
function drawNewBadge(
  ctx: CanvasRenderingContext2D,
  text: string,
  size: number,
  fontFamily: string,
) {
  if (!text || !text.trim()) return;
  const cx = 90;
  const cy = size * 0.42;
  const r = 56;
  // Outer ring
  ctx.beginPath();
  ctx.arc(cx, cy, r, 0, Math.PI * 2);
  ctx.fillStyle = "rgba(255,255,255,0.92)";
  ctx.fill();
  ctx.strokeStyle = "#E5C97A";
  ctx.lineWidth = 2;
  ctx.stroke();
  // Sunburst lines (decorative)
  ctx.strokeStyle = "#E5C97A";
  ctx.lineWidth = 1.5;
  for (let i = 0; i < 16; i++) {
    const angle = (i / 16) * Math.PI * 2;
    const x1 = cx + Math.cos(angle) * (r + 4);
    const y1 = cy + Math.sin(angle) * (r + 4);
    const x2 = cx + Math.cos(angle) * (r + 12);
    const y2 = cy + Math.sin(angle) * (r + 12);
    ctx.beginPath();
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2, y2);
    ctx.stroke();
  }
  // Text — split into "NEW" + small line if both present
  const parts = text.split(/[\s·]+/).filter(Boolean);
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillStyle = "#1A1A1A";
  if (parts.length >= 2 && /^[A-Za-z]+$/.test(parts[0])) {
    ctx.font = `900 22px ${fontFamily}`;
    ctx.fillText(parts[0].toUpperCase(), cx, cy - 10);
    ctx.font = `600 14px ${fontFamily}`;
    ctx.fillText(parts.slice(1).join(""), cx, cy + 12);
  } else {
    ctx.font = `700 16px ${fontFamily}`;
    ctx.fillText(text.slice(0, 6), cx, cy);
  }
}

/**
 * Draw a "wheat-spike" side badge — short text with two decorative
 * curved strokes flanking it, styled after the reference samples.
 */
function drawSideBadge(
  ctx: CanvasRenderingContext2D,
  text: string,
  cx: number,
  cy: number,
  fontFamily: string,
) {
  if (!text || !text.trim()) return;
  ctx.font = `600 18px ${fontFamily}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  const tw = ctx.measureText(text).width;
  // pill background
  const padX = 14;
  const w = tw + padX * 2;
  const h = 36;
  ctx.fillStyle = "rgba(255,255,255,0.88)";
  const r = h / 2;
  ctx.beginPath();
  ctx.moveTo(cx - w / 2 + r, cy - h / 2);
  ctx.arcTo(cx + w / 2, cy - h / 2, cx + w / 2, cy + h / 2, r);
  ctx.arcTo(cx + w / 2, cy + h / 2, cx - w / 2, cy + h / 2, r);
  ctx.arcTo(cx - w / 2, cy + h / 2, cx - w / 2, cy - h / 2, r);
  ctx.arcTo(cx - w / 2, cy - h / 2, cx + w / 2, cy - h / 2, r);
  ctx.closePath();
  ctx.fill();
  ctx.strokeStyle = "#E5C97A";
  ctx.lineWidth = 1.2;
  ctx.stroke();
  // wheat strokes (two angled lines on each side)
  ctx.strokeStyle = "#C9A95C";
  ctx.lineWidth = 1.2;
  for (const dir of [-1, 1]) {
    const baseX = cx + dir * (w / 2 + 6);
    for (let i = 0; i < 3; i++) {
      const yy = cy - 6 + i * 6;
      ctx.beginPath();
      ctx.moveTo(baseX, yy);
      ctx.lineTo(baseX + dir * 10, yy - 3);
      ctx.stroke();
    }
  }
  // text
  ctx.fillStyle = "#1A1A1A";
  ctx.fillText(text, cx, cy + 1);
}

/** Draw the brand string at the bottom-left, small and discreet. */
function drawBrand(ctx: CanvasRenderingContext2D, text: string, size: number, fontFamily: string) {
  if (!text || !text.trim()) return;
  ctx.font = `700 18px ${fontFamily}`;
  ctx.textAlign = "left";
  ctx.textBaseline = "alphabetic";
  ctx.fillStyle = "rgba(26,26,26,0.85)";
  ctx.fillText(text, 36, size - 28);
}

/** Wait for required webfonts to be ready (best-effort). */
async function waitForFonts(fontFamily: string): Promise<void> {
  if (typeof document === "undefined" || !document.fonts) return;
  // Pull just the first family name (the one next/font registered)
  const primary = fontFamily.split(",")[0].trim();
  try {
    await Promise.race([
      Promise.all([
        document.fonts.load(`900 56px ${primary}`),
        document.fonts.load(`700 32px ${primary}`),
        document.fonts.load(`500 20px ${primary}`),
      ]),
      new Promise((r) => setTimeout(r, 1500)),
    ]);
    await Promise.race([
      document.fonts.ready,
      new Promise((r) => setTimeout(r, 500)),
    ]);
  } catch {
    // Best-effort; system fallback handles the rest.
  }
}

export async function synthesizeTemplate1(
  baseImageUrl: string,
  copy: CopyData,
): Promise<string> {
  const fontFamily = getFontFamily();
  await waitForFonts(fontFamily);
  const img = await loadImage(baseImageUrl);

  const canvas = document.createElement("canvas");
  canvas.width = CANVAS_SIZE;
  canvas.height = CANVAS_SIZE;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Could not get 2D canvas context");

  // 1. base hero image
  drawCover(ctx, img, CANVAS_SIZE);

  // 2. soft top scrim for text readability
  drawTopScrim(ctx, CANVAS_SIZE);

  // 3. main title + subtitle + bullets
  const hasTwoLineMain = copy.main_title.length > 9;
  drawMainTitle(ctx, copy.main_title, CANVAS_SIZE, fontFamily);
  drawSubTitle(ctx, copy.sub_title, hasTwoLineMain, fontFamily);
  drawBullets(ctx, copy.bullets, hasTwoLineMain, !!copy.sub_title, fontFamily);

  // 4. left circular NEW badge
  drawNewBadge(ctx, copy.new_badge, CANVAS_SIZE, fontFamily);

  // 5. right side badges (麦穗 angle)
  const sideBadges = (copy.side_badges ?? []).slice(0, 2);
  if (sideBadges[0]) drawSideBadge(ctx, sideBadges[0], CANVAS_SIZE - 110, CANVAS_SIZE * 0.36, fontFamily);
  if (sideBadges[1]) drawSideBadge(ctx, sideBadges[1], CANVAS_SIZE - 110, CANVAS_SIZE * 0.46, fontFamily);

  // 6. brand at bottom-left
  drawBrand(ctx, copy.brand, CANVAS_SIZE, fontFamily);

  return canvas.toDataURL("image/png", 0.95);
}
